version: '3.7'
services:
    web:
        image: nginx:alpine
        container_name: web-nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql
    php:
        build:
            context: etc/php
            args:
                - PHP_VERSION=${PHP_VERSION}
        container_name: php_wp-cli
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        depends_on:
            - mysql
        links:
            - mysql:mysql
        restart: always

    composer:
        image: "composer"
        container_name: composer
        volumes:
            - "./web/app:/app"
        command: install

    # wp-cli:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     container_name: wp-cli
    #     volumes:
    #         - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    #         - "./web:/var/www/html"
    #     depends_on:
    #         - mysql
    #     links:
    #         - mysql:mysql
    #     restart: always

    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
             - './data/db:/var/lib/mysql:delegated'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: "${MYSQL_HOST}"
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        volumes:
            - ./etc/phpmyadmin/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
        env_file:
            - ".env"
        restart: always
        ports:
         - '8080:80'
        links:
        - mysql:mysql